/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by tools/gen_replay.py from none. Diagnostic only. */
#define B43_AC_POR_RADIO	0x01
#define B43_AC_POR_PHY		0x02
#define B43_AC_POR_TBL		0x04
#define B43_AC_POR_SHM		0x08
#define B43_AC_POR_CC		0x10
#define B43_AC_POR_PMU		0x20
static const u16 b43_ac_por_radio[][2] = {
	{ 0xffff, 0 },
};
static const u16 b43_ac_por_phy[][2] = {
	{ 0xffff, 0 },
};
static const struct { u16 id, off; u8 width; u32 val; } b43_ac_por_tbl[] = {
	{ 0xffff, 0, 0, 0 },
};
static const struct { u16 routing, off; u16 val; } b43_ac_por_shm[] = {
	{ 0xffff, 0, 0 },
};
/* chipcommon register writes (final values), offset from chipcommon base */
static const u32 b43_ac_por_cc[][2] = {
	{ 0xffff, 0 },
};
/* PMU indirect: kind 0 = chipcontrol, 1 = regcontrol */
static const struct { u8 kind, idx; u32 val; } b43_ac_por_pmu[] = {
	{ 0xff, 0, 0 },
};
