#!/usr/bin/env python3
"""Generate b43-src/tables_phy_ac.c from the acphytbl_info_rev0 dump.

Input: extracted/acphytbl_rev0/index.txt plus one .bin per table, written by
dump_tblinfo.java (Ghidra) from wl.ko. Data is little-endian as stored in
wl.ko. Table order is preserved: the vendor writes some table IDs twice and
the later write wins.
"""
import os
import re
import struct
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "extracted/acphytbl_rev0"
OUT = sys.argv[2] if len(sys.argv) > 2 else "b43-src/tables_phy_ac.c"

CTYPE = {8: ("u8", "<B", 1, "0x%02x"), 16: ("u16", "<H", 2, "0x%04x"),
         32: ("u32", "<I", 4, "0x%08x")}

entries = []
for line in open(os.path.join(SRC, "index.txt")):
    m = re.match(r"(\d+) (\S+) id=(\d+) offset=(\d+) count=(\d+) width=(\d+) file=(\S+)", line)
    idx, sym, tid, off, count, width, fname = m.groups()
    entries.append(dict(idx=int(idx), sym=sym, id=int(tid), offset=int(off),
                        count=int(count), width=int(width), file=fname))

out = ["// SPDX-License-Identifier: GPL-2.0-or-later",
       "/* AC-PHY rev 0/1 init tables. Generated by tools/gen_tables_phy_ac.py. */",
       "",
       '#include "b43.h"',
       '#include "tables_phy_ac.h"',
       ""]

for e in entries:
    ctype, fmt, size, vfmt = CTYPE[e["width"]]
    raw = open(os.path.join(SRC, e["file"]), "rb").read()
    assert len(raw) == e["count"] * size, e
    vals = [struct.unpack(fmt, raw[i:i + size])[0] for i in range(0, len(raw), size)]
    name = "b43_acphy_tbl_%02d" % e["idx"]
    e["name"] = name
    out.append("/* %s */" % e["sym"])
    out.append("static const %s %s[] = {" % (ctype, name))
    per = 8 if size >= 4 else 12
    for i in range(0, len(vals), per):
        out.append("\t" + ", ".join(vfmt % v for v in vals[i:i + per]) + ",")
    out.append("};")
    out.append("")

out.append("const struct b43_phy_ac_tbl b43_phy_ac_tbls_rev0[] = {")
for e in entries:
    out.append("\t{ %s, %d, %d, %d, %d }," % (e["name"], e["count"], e["id"],
                                             e["offset"], e["width"]))
out.append("};")
out.append("")
out.append("const unsigned int b43_phy_ac_tbls_rev0_n = ARRAY_SIZE(b43_phy_ac_tbls_rev0);")
out.append("")
open(OUT, "w").write("\n".join(out))
print("wrote %d tables to %s" % (len(entries), OUT))
