#!/usr/bin/env python3
"""Generate b43-src/phy_ac_por.h from a decode_trace.py output directory.

usage: gen_replay.py DECODED_DIR OUT_H [SOURCE_NAME] [ARRAY_PREFIX]

With no DECODED_DIR ("-"), writes empty arrays so the module builds.
"""
import os
import sys

TABLE_ACCESS_REGS = {0x00d, 0x00e, 0x00f, 0x010, 0x011}


def rows(path):
    if not path or not os.path.exists(path):
        return []
    with open(path) as f:
        return [ln.split() for ln in f if ln.strip()]


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    d, out = sys.argv[1], sys.argv[2]
    src = sys.argv[3] if len(sys.argv) > 3 else d
    pfx = sys.argv[4] if len(sys.argv) > 4 else "b43_ac_por"
    p = (lambda n: os.path.join(d, n)) if d != "-" else (lambda n: None)

    radio = [(int(r, 16), int(v, 16)) for r, v in rows(p("radio.txt"))]
    phy = [(int(r, 16), int(v, 16)) for r, v in rows(p("phy.txt"))
           if int(r, 16) not in TABLE_ACCESS_REGS]
    tbl = [(int(i), int(o), int(w), int(v, 16)) for i, o, w, v in rows(p("tables.txt"))]
    shm = [(int(r), int(o, 16), int(v, 16)) for r, o, v in rows(p("shm.txt"))
           if int(r) == 1]
    cc = [(int(o, 16), int(v, 16)) for o, v in rows(p("cc.txt"))]
    pmu = []
    for kind, idx in (("chipctl", 0), ("regctl", 1)):
        pmu += [(idx, int(i), int(v, 16)) for i, v in rows(p("pmu-%s.txt" % kind))
                if int(i) >= 0]

    L = ["/* SPDX-License-Identifier: GPL-2.0 */",
         "/* Generated by tools/gen_replay.py from %s. Diagnostic only. */" % src,
         "#ifndef B43_AC_POR_RADIO",
         "#define B43_AC_POR_RADIO\t0x01",
         "#define B43_AC_POR_PHY\t\t0x02",
         "#define B43_AC_POR_TBL\t\t0x04",
         "#define B43_AC_POR_SHM\t\t0x08",
         "#define B43_AC_POR_CC\t\t0x10",
         "#define B43_AC_POR_PMU\t\t0x20",
         "#endif",
         "static const u16 %s_radio[]" % pfx + "[2] = {"]
    L += ["\t{ 0x%04x, 0x%04x }," % x for x in radio] or ["\t{ 0xffff, 0 },"]
    L += ["};", "static const u16 %s_phy[]" % pfx + "[2] = {"]
    L += ["\t{ 0x%04x, 0x%04x }," % x for x in phy] or ["\t{ 0xffff, 0 },"]
    L += ["};", "static const struct { u16 id, off; u8 width; u32 val; } %s_tbl[]" % pfx + " = {"]
    L += ["\t{ %d, %d, %d, 0x%x }," % x for x in tbl] or ["\t{ 0xffff, 0, 0, 0 },"]
    L += ["};", "static const struct { u16 routing, off; u16 val; } %s_shm[]" % pfx + " = {"]
    L += ["\t{ %d, 0x%04x, 0x%04x }," % x for x in shm] or ["\t{ 0xffff, 0, 0 },"]
    L += ["};", "/* chipcommon register writes (final values), offset from chipcommon base */",
          "static const u32 %s_cc[]" % pfx + "[2] = {"]
    L += ["\t{ 0x%03x, 0x%08x }," % x for x in cc] or ["\t{ 0xffff, 0 },"]
    L += ["};", "/* PMU indirect: kind 0 = chipcontrol, 1 = regcontrol */",
          "static const struct { u8 kind, idx; u32 val; } %s_pmu[]" % pfx + " = {"]
    L += ["\t{ %d, %d, 0x%08x }," % x for x in pmu] or ["\t{ 0xff, 0, 0 },"]
    L += ["};"]
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    print("%s: radio %d phy %d tbl %d shm %d cc %d pmu %d" %
          (out, len(radio), len(phy), len(tbl), len(shm), len(cc), len(pmu)))


if __name__ == "__main__":
    main()
