#!/usr/bin/env python3
"""Generate b43-src/radio_2069.c from the chan_tuning_2069rev4 table in wl.ko.

Entry layout (58 x u16, little-endian), as consumed by the vendor driver's
channel-set code for radio 0x2069 revisions 3..8:
  [0]      channel number
  [1]      centre frequency (MHz)
  [2..51]  values for 50 radio registers (see phy_ac.c)
  [52..57] PHY BW1a..BW6 (0x371..0x376)
"""
import struct
import sys

WL = sys.argv[1] if len(sys.argv) > 1 else "extracted/wl.ko"
OUT = sys.argv[2] if len(sys.argv) > 2 else "b43-src/radio_2069.c"

DATA_FILE_OFF = 0x49C548   # .data section file offset
SYM_VALUE = 0x13E850       # chan_tuning_2069rev4
SYM_SIZE = 8932
ENTRY = 116

raw = open(WL, "rb").read()[DATA_FILE_OFF + SYM_VALUE:][:SYM_SIZE]
assert len(raw) == SYM_SIZE and SYM_SIZE % ENTRY == 0
entries = [struct.unpack("<58H", raw[i:i + ENTRY]) for i in range(0, SYM_SIZE, ENTRY)]

def row(vals):
    return ", ".join("0x%04x" % v for v in vals)

out = []
out.append("// SPDX-License-Identifier: GPL-2.0-or-later")
out.append("/* Radio 2069 rev 4 channel tuning table. Generated by tools/gen_radio_2069.py. */")
out.append("")
out.append('#include "b43.h"')
out.append('#include "radio_2069.h"')
out.append("")
out.append("const struct b43_radio_2069_chan b43_radio_2069r4_chans[] = {")
for e in entries:
    out.append("\t{ .channel = %d, .freq = %d," % (e[0], e[1]))
    out.append("\t  .radio = { %s }," % row(e[2:52]))
    out.append("\t  .bw = { %s } }," % row(e[52:58]))
out.append("};")
out.append("")
out.append("const unsigned int b43_radio_2069r4_chans_n = ARRAY_SIZE(b43_radio_2069r4_chans);")
out.append("")
open(OUT, "w").write("\n".join(out))
print("wrote %d entries to %s" % (len(entries), OUT))
