#!/usr/bin/env python3
"""Extract one wl channel-switch window from a decoded 5 GHz trace as an ordered op list.

usage: gen_switch_window.py SEQ_TXT FARROW_19B_HEX OCCURRENCE OUT_H [PREFIX]

The window starts at the radio-tune run before the Farrow write (phy 0x19b == FARROW_19B_HEX, n-th
occurrence, 1-based) and ends where the next channel's radio-tune run (>= 20 consecutive radio writes)
begins. Ops: 0 phy reg val | 1 radio reg val | 2 table id off val width | 3 delay us.
PHY table address/data port writes (0x0d-0x11) are left out: the "tbl" lines replace them.
"""
import sys

PORTS = {0xd, 0xe, 0xf, 0x10, 0x11}


def main():
    seq, far, occ, out = sys.argv[1], int(sys.argv[2], 16), int(sys.argv[3]), sys.argv[4]
    pfx = sys.argv[5] if len(sys.argv) > 5 else "b43_ac_win_ops"
    ops = [ln.split() for ln in open(seq)]
    hits = [i for i, o in enumerate(ops) if o[1] == "phy" and o[2] == "19b" and int(o[3], 16) == far]
    i0 = hits[occ - 1]
    s, run = i0, 0
    for j in range(i0, -1, -1):
        if ops[j][1] == "radio":
            run += 1
        elif ops[j][1] != "delay" and run >= 20:
            break
        elif ops[j][1] != "delay":
            run = 0
        s = j
    while s > 0 and ops[s - 1][1] in ("radio", "delay"):
        s -= 1
    e, run = i0, 0
    for j in range(i0, len(ops)):
        run = run + 1 if ops[j][1] == "radio" else 0
        if run >= 20:
            e = j - run + 1
            break
    rows = []
    for o in ops[s:e]:
        k = o[1]
        if k == "phy" and int(o[2], 16) not in PORTS:
            rows.append((0, int(o[2], 16), 0, int(o[3], 16), 0))
        elif k == "radio":
            rows.append((1, int(o[2], 16), 0, int(o[3], 16), 0))
        elif k == "tbl":
            rows.append((2, int(o[2], 16), int(o[3], 16), int(o[5], 16), int(o[4], 16)))
        elif k == "delay":
            rows.append((3, 0, 0, int(o[2], 16), 0))
    with open(out, "w") as f:
        f.write("/* SPDX-License-Identifier: GPL-2.0 */\n/* One wl channel switch, from %s lines %d-%d (19b=%#x, #%d). Generated by tools/gen_switch_window.py */\n" % (seq, s + 1, e, far, occ))
        f.write("static const struct { u8 t; u16 a, b; u32 v; u8 w; } %s[] = {\n" % pfx)
        for r in rows:
            f.write("\t{ %d, 0x%04x, 0x%04x, 0x%x, %d },\n" % r)
        f.write("};\n")
    c = {}
    for r in rows:
        c[r[0]] = c.get(r[0], 0) + 1
    print("lines %d-%d, ops: %s" % (s + 1, e, c))


main()
